// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ChooseDownloadDir() {
  return window['go']['main']['WeDropService']['ChooseDownloadDir']();
}

export function ClearClipboardHistory() {
  return window['go']['main']['WeDropService']['ClearClipboardHistory']();
}

export function ClearNotifications() {
  return window['go']['main']['WeDropService']['ClearNotifications']();
}

export function ControlLocalMedia(arg1) {
  return window['go']['main']['WeDropService']['ControlLocalMedia'](arg1);
}

export function CopyToClipboard(arg1) {
  return window['go']['main']['WeDropService']['CopyToClipboard'](arg1);
}

export function DeleteAppActionProfile(arg1) {
  return window['go']['main']['WeDropService']['DeleteAppActionProfile'](arg1);
}

export function GetDiagnostics() {
  return window['go']['main']['WeDropService']['GetDiagnostics']();
}

export function GetState() {
  return window['go']['main']['WeDropService']['GetState']();
}

export function GetWorkspaceButtons() {
  return window['go']['main']['WeDropService']['GetWorkspaceButtons']();
}

export function ListAppActionProfiles() {
  return window['go']['main']['WeDropService']['ListAppActionProfiles']();
}

export function MarkNotificationsRead() {
  return window['go']['main']['WeDropService']['MarkNotificationsRead']();
}

export function OpenDownloadsFolder() {
  return window['go']['main']['WeDropService']['OpenDownloadsFolder']();
}

export function PairDevice(arg1) {
  return window['go']['main']['WeDropService']['PairDevice'](arg1);
}

export function PushClipboard() {
  return window['go']['main']['WeDropService']['PushClipboard']();
}

export function RespondToPairing(arg1, arg2) {
  return window['go']['main']['WeDropService']['RespondToPairing'](arg1, arg2);
}

export function RespondToTransfer(arg1, arg2) {
  return window['go']['main']['WeDropService']['RespondToTransfer'](arg1, arg2);
}

export function RevealFile(arg1) {
  return window['go']['main']['WeDropService']['RevealFile'](arg1);
}

export function SaveAppActionProfile(arg1) {
  return window['go']['main']['WeDropService']['SaveAppActionProfile'](arg1);
}

export function SaveWorkspaceButtons(arg1) {
  return window['go']['main']['WeDropService']['SaveWorkspaceButtons'](arg1);
}

export function SelectFiles() {
  return window['go']['main']['WeDropService']['SelectFiles']();
}

export function SendFiles(arg1, arg2) {
  return window['go']['main']['WeDropService']['SendFiles'](arg1, arg2);
}

export function SendKey(arg1, arg2) {
  return window['go']['main']['WeDropService']['SendKey'](arg1, arg2);
}

export function SendMediaCommand(arg1, arg2) {
  return window['go']['main']['WeDropService']['SendMediaCommand'](arg1, arg2);
}

export function SendMediaSeek(arg1, arg2) {
  return window['go']['main']['WeDropService']['SendMediaSeek'](arg1, arg2);
}

export function SendMouseClick(arg1, arg2) {
  return window['go']['main']['WeDropService']['SendMouseClick'](arg1, arg2);
}

export function SendMouseMove(arg1, arg2, arg3) {
  return window['go']['main']['WeDropService']['SendMouseMove'](arg1, arg2, arg3);
}

export function SendPresentation(arg1, arg2) {
  return window['go']['main']['WeDropService']['SendPresentation'](arg1, arg2);
}

export function SendScroll(arg1, arg2) {
  return window['go']['main']['WeDropService']['SendScroll'](arg1, arg2);
}

export function SendText(arg1, arg2) {
  return window['go']['main']['WeDropService']['SendText'](arg1, arg2);
}

export function SetDeviceName(arg1) {
  return window['go']['main']['WeDropService']['SetDeviceName'](arg1);
}

export function SetDevicePermission(arg1, arg2, arg3) {
  return window['go']['main']['WeDropService']['SetDevicePermission'](arg1, arg2, arg3);
}

export function UnpairDevice(arg1) {
  return window['go']['main']['WeDropService']['UnpairDevice'](arg1);
}

export function UpdateSettings(arg1) {
  return window['go']['main']['WeDropService']['UpdateSettings'](arg1);
}
