// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {protocol} from '../models';
import {storage} from '../models';

export function AcceptPairing(arg1:string):Promise<void>;

export function EnsureModels():Promise<protocol.PairingReq|protocol.PairingResp>;

export function GetDevices():Promise<Array<protocol.DiscoveryMessage>>;

export function GetSettings():Promise<storage.DeviceConfig>;

export function GetTrustedDevices():Promise<Array<storage.TrustedDevice>>;

export function RejectPairing(arg1:string):Promise<void>;

export function RemoveTrustedDevice(arg1:string):Promise<void>;

export function RequestPairing(arg1:string):Promise<void>;

export function SelectFile():Promise<string>;

export function SendFile(arg1:string,arg2:string):Promise<void>;

export function SetAutoSyncClipboard(arg1:boolean):Promise<void>;

export function SyncClipboard(arg1:string,arg2:string):Promise<void>;
