// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AcceptPairing(arg1) {
  return window['go']['main']['WeDropService']['AcceptPairing'](arg1);
}

export function EnsureModels() {
  return window['go']['main']['WeDropService']['EnsureModels']();
}

export function GetDevices() {
  return window['go']['main']['WeDropService']['GetDevices']();
}

export function GetSettings() {
  return window['go']['main']['WeDropService']['GetSettings']();
}

export function GetTrustedDevices() {
  return window['go']['main']['WeDropService']['GetTrustedDevices']();
}

export function RejectPairing(arg1) {
  return window['go']['main']['WeDropService']['RejectPairing'](arg1);
}

export function RemoveTrustedDevice(arg1) {
  return window['go']['main']['WeDropService']['RemoveTrustedDevice'](arg1);
}

export function RequestPairing(arg1) {
  return window['go']['main']['WeDropService']['RequestPairing'](arg1);
}

export function SelectFile() {
  return window['go']['main']['WeDropService']['SelectFile']();
}

export function SendFile(arg1, arg2) {
  return window['go']['main']['WeDropService']['SendFile'](arg1, arg2);
}

export function SetAutoSyncClipboard(arg1) {
  return window['go']['main']['WeDropService']['SetAutoSyncClipboard'](arg1);
}

export function SyncClipboard(arg1, arg2) {
  return window['go']['main']['WeDropService']['SyncClipboard'](arg1, arg2);
}
