// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';
import {storage} from '../models';

export function ChooseDownloadDir():Promise<string>;

export function ClearClipboardHistory():Promise<void>;

export function ClearNotifications():Promise<void>;

export function ControlLocalMedia(arg1:string):Promise<void>;

export function CopyToClipboard(arg1:string):Promise<void>;

export function GetDiagnostics():Promise<main.Diagnostics>;

export function GetState():Promise<main.AppState>;

export function MarkNotificationsRead():Promise<void>;

export function OpenDownloadsFolder():Promise<void>;

export function PairDevice(arg1:string):Promise<void>;

export function PushClipboard():Promise<void>;

export function RespondToPairing(arg1:string,arg2:boolean):Promise<void>;

export function RespondToTransfer(arg1:string,arg2:boolean):Promise<void>;

export function RevealFile(arg1:string):Promise<void>;

export function SelectFiles():Promise<Array<string>>;

export function SendFiles(arg1:string,arg2:Array<string>):Promise<void>;

export function SendMediaCommand(arg1:string,arg2:string):Promise<void>;

export function SetDeviceName(arg1:string):Promise<void>;

export function SetDevicePermission(arg1:string,arg2:string,arg3:boolean):Promise<void>;

export function UnpairDevice(arg1:string):Promise<void>;

export function UpdateSettings(arg1:storage.Settings):Promise<void>;
